# Generated by Django 4.2.1 on 2023-05-18 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('entrenador', models.CharField(max_length=100)),
                ('juegosGanados', models.IntegerField()),
                ('juegosPerdidos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estadios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ligas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('poblacion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numeroPlayera', models.IntegerField()),
                ('posicion', models.CharField(max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipos')),
            ],
        ),
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('contrincante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipos')),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estadios')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ligas')),
            ],
        ),
        migrations.AddField(
            model_name='estadios',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ligas'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ligas'),
        ),
        migrations.CreateModel(
            name='Cedulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('horaInicio', models.TimeField(null=True)),
                ('horaFin', models.TimeField(null=True)),
                ('resultado', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.juegos')),
            ],
        ),
        migrations.CreateModel(
            name='Arbitros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='uploads/')),
                ('nombre', models.CharField(max_length=100)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ligas')),
            ],
        ),
    ]
