# Generated by Django 4.2.1 on 2023-05-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_equipos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadios',
            name='imagen',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
